### ISSUE TITLE
Close room when unused

### ISSUE THREAD

**Issue by ThibaudREY** [ThibaudREY/conferly#17]
- Periodically ping the websocket for users in the room, remove if no one is left (check for dirty leaving)
- Implement leaving method that properly unregisters (Not sure if we can guaranty that call when the tab is savagely closed)

**Comment by ThibaudREY** [comment]
Best to fire room removal on initiator 'onbeforeunload' event, since no one would be able to join after that

**Comment by AnthonyPierrat** [comment]
Should we also "kill" the room when the initiator leaves ?
