### ISSUE TITLE
Dependency Injection error

### ISSUE THREAD

**Issue by ghost** [ThibaudREY/conferly#36]

**Comment by ghost** [comment]
How to use the DI with inversify-react :
- setup services in ioc.ts (same as inversify)
- just add decorator @resolve(YOUR_SERVICE) in component

**Comment by ThibaudREY** [comment]
Just not working with nested dependencies

**Comment by ghost** [comment]
fixed here 215a37c90df4978506851271272d1bd55f897b29 🛠
