### ISSUE TITLE
Hello message from Initiator

### ISSUE THREAD

**Issue by ThibaudREY** [ThibaudREY/conferly#40]
Send a hello message from pc initiator (not session initiator) to allow non-initiator to send messages

**Comment by ThibaudREY** [comment]
This message should include peer state such as mic toggle, video toggle, ...
And should hence be bidirectional.

**Comment by ghost** [comment]
Closing this as we know that the issue is not related to send a message from pc but from "timing" "latency".

We should open a new issue.
